import { Dimensions, Platform, StyleSheet } from 'react-native';

const { height: screenHeight } = Dimensions.get('window');

export const styles = StyleSheet.create({
  gradientContainer: {
    flex: 1,
    backgroundColor: '#FFFFFF',
  },
  container: {
    flex: 1,
    paddingTop: Platform.OS === 'ios' ? 50 : 40,
  },
  // Notification Header
  notificationHeader: {
    position: 'absolute',
    top: Platform.OS === 'ios' ? 50 : 40,
    right: 12,
    zIndex: 1000,
    paddingTop: 8,
  },
  notificationIconButton: {
    width: 44,
    height: 44,
    borderRadius: 22,
    backgroundColor: '#FFFFFF',
    justifyContent: 'center',
    alignItems: 'center',
    shadowColor: '#FF6B6B',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.3,
    shadowRadius: 4,
    elevation: 5,
    borderWidth: 1,
    borderColor: '#FFE5E5',
    position: 'relative',
  },
  notificationBadge: {
    position: 'absolute',
    top: -2,
    right: -2,
    backgroundColor: '#FF3B30',
    borderRadius: 10,
    minWidth: 20,
    height: 20,
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: 4,
    borderWidth: 2,
    borderColor: '#FFFFFF',
  },
  notificationBadgeText: {
    color: '#FFFFFF',
    fontSize: 10,
    fontWeight: 'bold',
  },
  scrollView: {
    flex: 1,
  },
  scrollContent: {
    flexGrow: 1,
    paddingBottom: 100,
    paddingHorizontal: 12,
  },
  newReportBanner: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: 'rgba(52, 199, 89, 0.1)',
    borderRadius: 12,
    padding: 12,
    marginHorizontal: 12,
    marginTop: 12,
    marginBottom: 8,
    borderWidth: 1,
    borderColor: 'rgba(52, 199, 89, 0.3)',
    gap: 8,
  },
  newReportBannerText: {
    fontSize: 14,
    fontWeight: '600',
    color: '#34C759',
  },
  // Active Case Banner
  activeCaseBanner: {
    marginHorizontal: 12,
    marginTop: 12,
    marginBottom: 16,
  },
  activeCaseBannerBlur: {
    borderRadius: 16,
    overflow: 'hidden',
    borderWidth: 1.5,
    borderColor: 'rgba(255, 107, 107, 0.4)',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.2,
    shadowRadius: 8,
    elevation: 5,
  },
  activeCaseBannerContent: {
    backgroundColor: 'rgba(255, 255, 255, 0.95)',
    padding: 16,
  },
  activeCaseHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 12,
  },
  activeCaseIconContainer: {
    width: 48,
    height: 48,
    borderRadius: 12,
    backgroundColor: 'rgba(255, 107, 107, 0.1)',
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 12,
  },
  activeCaseHeaderText: {
    flex: 1,
  },
  activeCaseTitle: {
    fontSize: 18,
    fontWeight: '800',
    color: '#1a1a1a',
    marginBottom: 6,
  },
  activeCaseStatusContainer: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  activeCaseStatusBadge: {
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 12,
  },
  statusBadgePending: {
    backgroundColor: '#FFA500',
  },
  statusBadgeResponding: {
    backgroundColor: '#007AFF',
  },
  activeCaseStatusText: {
    fontSize: 12,
    fontWeight: '700',
    color: '#FFFFFF',
    textTransform: 'uppercase',
  },
  activeCaseDetails: {
    marginTop: 8,
    paddingTop: 12,
    borderTopWidth: 1,
    borderTopColor: 'rgba(0, 0, 0, 0.1)',
  },
  activeCaseDetailRow: {
    flexDirection: 'row',
    marginBottom: 8,
    alignItems: 'flex-start',
  },
  activeCaseDetailLabel: {
    fontSize: 13,
    fontWeight: '600',
    color: '#666',
    minWidth: 100,
    marginRight: 8,
  },
  activeCaseDetailValue: {
    fontSize: 13,
    fontWeight: '500',
    color: '#1a1a1a',
    flex: 1,
  },

  // Welcome Card - Neumorphism (Dual Shadows)
  welcomeCard: {
    backgroundColor: '#FFE5E5',
    borderColor: 'rgba(255, 255, 255, 0.6)',
    borderRadius: 24,
    padding: 20,
    marginTop: 10,
    marginBottom: 24,
    // Light shadow (top-left) - raised effect
    shadowColor: '#D1B0B0',
    shadowOffset: { width: -8, height: -8 },
    shadowOpacity: 0.8,
    shadowRadius: 12,
    elevation: 6,
    borderWidth: 1,
  },
  welcomeHeader: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  avatarContainer: {
    width: 60,
    height: 60,
    borderRadius: 30,
    backgroundColor: '#FF6B6B',
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 16,
    // Dark shadow (bottom-right) - depth
    shadowColor: '#CC5555',
    shadowOffset: { width: 4, height: 4 },
    shadowOpacity: 0.5,
    shadowRadius: 6,
    elevation: 5,
    borderWidth: 2,
    borderColor: '#fff',
  },
  avatarText: {
    fontSize: 24,
    fontWeight: 'bold',
    color: '#fff',
  },
  welcomeTextContainer: {
    flex: 1,
  },
  welcomeTitle: {
    fontSize: 24,
    fontWeight: 'bold',
    color: '#1a1a1a',
    marginBottom: 4,
  },
  welcomeSubtitle: {
    fontSize: 14,
    color: '#666',
  },

  // Sections
  section: {
    marginBottom: 24,
    marginTop: 8,
    paddingHorizontal: 4,
  },
  descriptionSection: {
    marginBottom: 12,
    marginTop: 12,
  },
  emergencyContactSection: {
    marginBottom: 20,
    marginTop: 100,
    paddingBottom: 30,
  },
  sectionTitleContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 24,
    paddingHorizontal: 2,
  },
  sectionTitle: {
    fontSize: 20,
    fontWeight: '800',
    color: '#fff',
    letterSpacing: 0.5,
    marginBottom: 16,
    marginLeft: 4,
    textShadowColor: 'rgba(0, 0, 0, 0.1)',
    textShadowOffset: { width: 0, height: 1 },
    textShadowRadius: 2,
  },
  descriptionSectionTitle: {
    fontSize: 24,
    fontWeight: 'bold',
    color: '#FFFFFF',
    marginBottom: 12,
    textAlign: 'left',
  },
  addButton: {
    width: 44,
    height: 44,
    borderRadius: 22,
    backgroundColor: '#F5F5F5',
    justifyContent: 'center',
    alignItems: 'center',
    // Light shadow (top-left) - raised effect
    shadowColor: '#D1B0B0',
    shadowOffset: { width: -5, height: -5 },
    shadowOpacity: 0.8,
    shadowRadius: 10,
    elevation: 6,
    borderWidth: 0,
  },

  // SOS Button
  sosButtonContainer: {
    justifyContent: 'center',
    alignItems: 'center',
    width: '100%',
    alignSelf: 'center',
    marginTop: 150,
    marginBottom: 30,
    paddingVertical: 20,
  },
  sosButtonContainerExpanded: {
    marginTop: 60, // Reduced margin when active case is expanded
  },
  // Neumorphism SOS Button (Dual Shadows)
  sosButtonNeumorphic: {
    backgroundColor: '#FFFFFF',
    alignItems: 'center',
    justifyContent: 'center',
    // Light shadow (top-left) - raised effect
    shadowColor: '#FF3B30',
    shadowOffset: { width: -8, height: -8 },
    shadowOpacity: 0.3,
    shadowRadius: 16,
    elevation: 12,
    borderWidth: 2,
    borderColor: '#FFE5E5',
  },
  sosButtonInner: {
    backgroundColor: '#FF6B6B',
    alignItems: 'center',
    justifyContent: 'center',
    // Dark shadow (bottom-right) - depth
    shadowColor: '#CC0000',
    shadowOffset: { width: 6, height: 6 },
    shadowOpacity: 0.5,
    shadowRadius: 10,
    elevation: 8,
    borderWidth: 3,
    borderColor: 'rgba(255, 255, 255, 0.3)',
  },
  sosButtonContent: {
    alignItems: 'center',
    justifyContent: 'center',
    gap: 2,
  },
  sosButtonText: {
    fontWeight: '900',
    color: '#FFFFFF',
    letterSpacing: 6,
    textAlign: 'center',
    textShadowColor: 'rgba(0, 0, 0, 0.4)',
    textShadowOffset: { width: 0, height: 3 },
    textShadowRadius: 6,
  },
  sosButtonSubtext: {
    fontWeight: '700',
    color: '#FFFFFF',
    letterSpacing: 2,
    textAlign: 'center',
    marginTop: 2,
    opacity: 0.95,
    textShadowColor: 'rgba(0, 0, 0, 0.3)',
    textShadowOffset: { width: 0, height: 1 },
    textShadowRadius: 3,
  },
  cancelPanel: {
    marginTop: 20,
    padding: 16,
    backgroundColor: '#FFFFFF',
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#FFFFFF',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
    alignItems: 'center',
  },
  cancelPanelText: {
    color: '#666',
    fontSize: 16,
    textAlign: 'center',
    marginBottom: 12,
    fontWeight: '500',
  },
  cancelButton: {
    paddingVertical: 14,
    paddingHorizontal: 32,
    backgroundColor: '#F5F5F5',
    borderRadius: 10,
    width: '100%',
    borderWidth: 1,
    borderColor: '#E0E0E0',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.05,
    shadowRadius: 2,
    elevation: 2,
  },
  cancelButtonText: {
    color: '#333',
    fontSize: 16,
    textAlign: 'center',
    fontWeight: '600',
  },

  // Activity
  activityCard: {
    backgroundColor: '#FFE5E5',
    borderRadius: 16,
    padding: 16,
    minHeight: 80,
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: '#FFFFFF',
    shadowColor: '#D1B0B0',
    shadowOffset: { width: 4, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 5,
  },
  activityItem: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 12,
  },
  activityText: {
    fontSize: 14,
    color: '#1a1a1a',
    marginLeft: 12,
    flex: 1,
  },
  noActivityText: {
    fontSize: 14,
    color: '#666',
    textAlign: 'center',
    fontStyle: 'italic',
  },

  // Emergency Contact - Neumorphism (Dual Shadows)
  contactCard: {
    backgroundColor: '#F5F5F5',
    borderRadius: 24,
    padding: 20,
    marginBottom: 16,
    // Light shadow (top-left) - raised effect
    shadowColor: '#D1B0B0',
    shadowOffset: { width: 8, height: 8 },
    shadowOpacity: 0.5,
    shadowRadius: 12,
    elevation: 10,
    borderWidth: 0,
    overflow: 'hidden',
  },
  contactHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 12,
    position: 'relative',
  },
  contactAvatarContainer: {
    marginRight: 12,
    width: 48,
    height: 48,
    borderRadius: 24,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#FFE5E5',
    // Light shadow (top-left) - raised effect
    shadowColor: '#D4A5A5',
    shadowOffset: { width: -4, height: -4 },
    shadowOpacity: 0.6,
    shadowRadius: 4,
    elevation: 4,
    borderWidth: 2,
    borderColor: '#FFFFFF',
  },
  contactInfo: {
    flex: 1,
    paddingTop: 2,
  },
  contactNameInput: {
    fontSize: 16,
    fontWeight: '800',
    color: '#1a1a1a',
    marginBottom: 4,
    paddingVertical: 2,
    paddingHorizontal: 0,
    borderBottomWidth: 0,
    backgroundColor: 'transparent',
    letterSpacing: 0.2,
    lineHeight: 20,
  },
  contactDetailInput: {
    fontSize: 13,
    color: '#666',
    marginBottom: 3,
    paddingVertical: 2,
    paddingHorizontal: 0,
    borderBottomWidth: 0,
    backgroundColor: 'transparent',
    lineHeight: 18,
    fontWeight: '500',
  },
  contactInput: {
    fontSize: 15,
    color: '#1a1a1a',
    marginBottom: 12,
    paddingVertical: 8,
    paddingHorizontal: 0,
    borderBottomWidth: 1.5,
    borderBottomColor: 'rgba(255, 107, 107, 0.2)',
    backgroundColor: 'transparent',
    fontWeight: '500',
  },
  deleteButton: {
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: '#F5F5F5',
    justifyContent: 'center',
    alignItems: 'center',
    marginTop: 0,
    borderWidth: 0,
    // Dark shadow (bottom-right) - inset/pressed effect
    shadowColor: '#CCCCCC',
    shadowOffset: { width: 4, height: 4 },
    shadowOpacity: 0.4,
    shadowRadius: 6,
    elevation: 3,
  },
  contactName: {
    fontSize: 16,
    fontWeight: '600',
    color: '#1a1a1a',
    marginBottom: 4,
  },
  contactNumber: {
    fontSize: 14,
    color: '#666',
  },
  contactActionButtons: {
    flexDirection: 'row',
    gap: 10,
    marginTop: 4,
  },
  callButton: {
    flex: 1,
    backgroundColor: '#FF6B6B',
    borderRadius: 16,
    paddingVertical: 12,
    alignItems: 'center',
    justifyContent: 'center',
    // Dark shadow (bottom-right) - depth
    shadowColor: '#CC5555',
    shadowOffset: { width: 5, height: 5 },
    shadowOpacity: 0.5,
    shadowRadius: 10,
    elevation: 6,
    overflow: 'hidden',
    borderWidth: 2,
    borderColor: 'rgba(255, 255, 255, 0.2)',
  },
  callButtonText: {
    color: '#FFFFFF',
    fontSize: 13,
    fontWeight: '800',
    letterSpacing: 0.5,
    textTransform: 'uppercase',
  },
  messageButton: {
    flex: 1,
    flexDirection: 'row', // align icon and text
    backgroundColor: '#F5F5F5', // Gray background
    borderRadius: 16,
    paddingVertical: 12, // Matches the Call button height
    alignItems: 'center',
    justifyContent: 'center',

    // THE FIX: Red Outline, No White Border
    borderWidth: 2,
    borderColor: '#FF6B6B',
    borderBottomWidth: 2, // Explicitly set this to ensure no underlying white line overrides it

    // Soft Shadow
    shadowColor: '#D1B0B0',
    shadowOffset: { width: 3, height: 3 },
    shadowOpacity: 0.3,
    shadowRadius: 5,
    elevation: 3,
  },
  messageButtonText: {
    color: '#FF6B6B', // Red Text
    fontSize: 13,
    fontWeight: '800',
    letterSpacing: 0.5,
    textTransform: 'uppercase',
    textDecorationLine: 'none', // Ensures no underline
  },
  disabledButton: {
    opacity: 0.35,
  },
  // Modal Styles
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  modalContent: {
    backgroundColor: '#fff',
    borderRadius: 24,
    width: '90%',
    maxWidth: 400,
    maxHeight: '85%',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.3,
    shadowRadius: 20,
    elevation: 10,
  },
  modalHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: 24,
    borderBottomWidth: 0,
  },
  modalTitle: {
    fontSize: 22,
    fontWeight: '800',
    color: '#1a1a1a',
    letterSpacing: 0.5,
  },
  modalCloseButton: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: '#F5F5F5',
    justifyContent: 'center',
    alignItems: 'center',
    // Light shadow (top-left) - raised effect
    shadowColor: '#FFFFFF',
    shadowOffset: { width: -3, height: -3 },
    shadowOpacity: 0.7,
    shadowRadius: 6,
    elevation: 3,
    borderWidth: 0,
  },
  modalBody: {
    padding: 24,
  },
  inputContainer: {
    marginBottom: 20,
  },
  inputLabel: {
    fontSize: 15,
    fontWeight: '700',
    color: '#1a1a1a',
    marginBottom: 10,
    letterSpacing: 0.3,
  },
  input: {
    borderWidth: 0,
    borderRadius: 16,
    padding: 16,
    fontSize: 16,
    color: '#1a1a1a',
    backgroundColor: '#F5F5F5',
    // Light shadow (top-left) - raised effect
    shadowColor: '#FFFFFF',
    shadowOffset: { width: -4, height: -4 },
    shadowOpacity: 0.7,
    shadowRadius: 8,
    elevation: 4,
  },
  modalButtonContainer: {
    flexDirection: 'row',
    gap: 12,
    marginTop: 8,
    marginBottom: 8,
  },
  modalCancelButton: {
    flex: 1,
    borderRadius: 16,
    paddingVertical: 16,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#F5F5F5',
    borderWidth: 0,
    // Light shadow (top-left) - raised effect
    shadowColor: '#FFFFFF',
    shadowOffset: { width: -4, height: -4 },
    shadowOpacity: 0.7,
    shadowRadius: 8,
    elevation: 4,
  },
  modalCancelButtonText: {
    fontSize: 16,
    fontWeight: '700',
    color: '#666',
    letterSpacing: 0.5,
  },
  modalSaveButton: {
    flex: 1,
    borderRadius: 16,
    overflow: 'hidden',
    // Dark shadow (bottom-right) - depth
    shadowColor: '#CC5555',
    shadowOffset: { width: 5, height: 5 },
    shadowOpacity: 0.5,
    shadowRadius: 10,
    elevation: 6,
    borderWidth: 2,
    borderColor: 'rgba(255, 255, 255, 0.2)',
  },
  modalSaveButtonGradient: {
    paddingVertical: 16,
    paddingHorizontal: 32,
    alignItems: 'center',
    justifyContent: 'center',
  },
  modalSaveButtonText: {
    fontSize: 16,
    fontWeight: '800',
    color: '#FFFFFF',
    letterSpacing: 0.8,
    textTransform: 'uppercase',
  },
  contactActions: {
    flexDirection: 'column',
    alignItems: 'center',
    gap: 10,
    marginLeft: 12,
    justifyContent: 'flex-start',
    paddingTop: 4,
  },
  contactActionButton: {
    width: 44,
    height: 44,
    borderRadius: 22,
    backgroundColor: '#fff',
    justifyContent: 'center',
    alignItems: 'center',
    shadowColor: '#FF6B6B',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.15,
    shadowRadius: 6,
    elevation: 4,
    borderWidth: 1,
    borderColor: 'rgba(255, 107, 107, 0.1)',
  },
  noContactText: {
    fontSize: 14,
    color: '#666',
    textAlign: 'center',
    fontStyle: 'italic',
    flex: 1,
    paddingVertical: 20,
  },

  // Report Screen
  reportHeader: {
    paddingHorizontal: 12,
    paddingTop: 16,
    paddingBottom: 20,
    marginBottom: 12,
  },
  reportHeaderBlur: {
    borderRadius: 24,
    overflow: 'hidden',
    borderWidth: 1.5,
    borderColor: 'rgba(255, 255, 255, 0.6)',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.25,
    shadowRadius: 20,
    elevation: 10,
  },
  reportHeaderContent: {
    flexDirection: 'row',
    alignItems: 'center',
    padding: 16,
    backgroundColor: 'rgba(255, 255, 255, 0.4)',
  },
  reportHeaderIconContainer: {
    width: 56,
    height: 56,
    borderRadius: 18,
    marginRight: 12,
    overflow: 'hidden',
    borderWidth: 1.5,
    borderColor: 'rgba(255, 255, 255, 0.9)',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.2,
    shadowRadius: 8,
    elevation: 5,
  },
  reportHeaderIconBlur: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: 16,
    backgroundColor: 'rgba(255, 255, 255, 0.2)',
  },
  reportHeaderTextContainer: {
    flex: 1,
  },
  reportHeaderTitle: {
    fontSize: 28,
    fontWeight: '900',
    color: '#FFFFFF',
    marginBottom: 4,
    letterSpacing: 0.5,
    textShadowColor: 'rgba(0,0,0,0.1)',
    textShadowOffset: { width: 0, height: 2 },
    textShadowRadius: 4,
  },
  reportHeaderSubtitle: {
    fontSize: 14,
    fontWeight: '600',
    color: 'rgba(255, 255, 255, 0.9)',
    letterSpacing: 0.2,
  },
  // Category Grid
  categoryGridContainer: {
    marginTop: 12,
  },
  hexagonalGridContainer: {
    marginTop: 12,
    marginBottom: 20,
    alignItems: 'center',
    justifyContent: 'center',
  },
  guideButton: {
    padding: 10,
    borderRadius: 25,
    backgroundColor: 'rgba(255, 255, 255, 0.9)',
    justifyContent: 'center',
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.2,
    shadowRadius: 4,
    elevation: 3,
    borderWidth: 1,
    borderColor: 'rgba(255, 107, 107, 0.3)',
  },
  categoryGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'space-between',
    position: 'relative',
    paddingHorizontal: 12,
    paddingVertical: 12,
    minHeight: 280,
  },
  categoryButton: {
    width: '48%',
    aspectRatio: 1,
    borderRadius: 25,
    overflow: 'hidden',
    marginBottom: 12,
    shadowColor: '#FF6B6B',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.15,
    shadowRadius: 8,
    elevation: 5,
    borderWidth: 3,
    borderColor: '#FFE5E5',
  },
  // Top-Left Button (Curved near circle - top-right and bottom-left corners)
  topLeftCurve: {
    borderTopLeftRadius: 8,
    borderTopRightRadius: 40,
    borderBottomLeftRadius: 40,
    borderBottomRightRadius: 8,
  },
  // Top-Right Button (Curved near circle - top-left and bottom-right corners)
  topRightCurve: {
    borderTopRightRadius: 8,
    borderTopLeftRadius: 40,
    borderBottomRightRadius: 40,
    borderBottomLeftRadius: 8,
  },
  // Bottom-Left Button (Curved near circle - top-left and bottom-right corners)
  bottomLeftCurve: {
    borderBottomLeftRadius: 8,
    borderTopLeftRadius: 40,
    borderBottomRightRadius: 40,
    borderTopRightRadius: 8,
  },
  // Bottom-Right Button (Curved near circle - top-right and bottom-left corners)
  bottomRightCurve: {
    borderBottomRightRadius: 10,
    borderTopRightRadius: 40,
    borderBottomLeftRadius: 40,
    borderTopLeftRadius: 10,
  },
  categoryButtonGradient: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    padding: 16,
  },
  categoryButtonText: {
    fontSize: 14,
    fontWeight: '600',
    color: '#FF6B6B',
    marginTop: 12,
    textAlign: 'center',
  },
  categoryFabButton: {
    position: 'absolute',
    top: '50%',
    left: '50%',
    width: 80,
    height: 80,
    borderRadius: 40,
    marginLeft: -30,
    marginTop: -30,
    zIndex: 10,
    shadowColor: '#FF6B6B',
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.3,
    shadowRadius: 12,
    elevation: 8,
    borderWidth: 3,
    borderColor: '#FFFFFF',
  },
  categoryFabGradient: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: 35,
  },
  categoryFabIcon: {
    textAlign: 'center',
    textAlignVertical: 'center',
  },
  reportTitle: {
    fontSize: 28,
    fontWeight: 'bold',
    color: '#fff',
    marginBottom: 8,
    textShadowColor: 'rgba(0, 0, 0, 0.2)',
    textShadowOffset: { width: 0, height: 1 },
    textShadowRadius: 2,
  },
  reportSubtitle: {
    fontSize: 14,
    color: 'rgba(255, 255, 255, 0.9)',
  },
  reportTypesGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'space-between',
  },
  reportTypeCard: {
    width: '48%',
    backgroundColor: '#fff',
    borderRadius: 16,
    padding: 20,
    alignItems: 'center',
    marginBottom: 12,
    borderWidth: 2,
    borderColor: '#E0E0E0',
    position: 'relative',
  },
  reportTypeCardSelected: {
    borderWidth: 2,
    backgroundColor: '#FFF5F5',
  },
  reportTypeText: {
    fontSize: 14,
    fontWeight: '500',
    color: '#666',
    marginTop: 8,
  },
  checkmark: {
    position: 'absolute',
    top: 8,
    right: 8,
    width: 24,
    height: 24,
    borderRadius: 12,
    justifyContent: 'center',
    alignItems: 'center',
  },
  descriptionContainer: {
    backgroundColor: 'rgba(255, 255, 255, 0.95)',
    borderRadius: 16,
    padding: 12,
    marginTop: 12,
    marginBottom: 12,
  },
  descriptionInput: {
    minHeight: 150,
    fontSize: 16,
    color: '#000000',
    textAlignVertical: 'top',
    paddingTop: 10,
    paddingBottom: 10,
    paddingHorizontal: 10,
  },
  characterCount: {
    fontSize: 12,
    color: '#999',
    marginTop: 4,
    textAlign: 'right',
  },
  // Role Selection
  roleContainer: {
    flexDirection: 'row',
    gap: 12,
    marginTop: 12,
  },
  roleButton: {
    flex: 1,
    backgroundColor: 'rgba(255, 255, 255, 0.95)',
    borderRadius: 16,
    padding: 12,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 2,
    borderColor: '#E0E0E0',
    position: 'relative',
    minHeight: 100,
  },
  roleButtonSelected: {
    borderColor: '#E0E0E0',
    backgroundColor: 'rgba(255, 255, 255, 0.95)',
  },
  roleButtonText: {
    fontSize: 16,
    fontWeight: '500',
    color: '#666',
    marginTop: 8,
  },
  roleButtonTextSelected: {
    color: '#FF6B6B',
    fontWeight: '600',
  },
  roleCheckmark: {
    position: 'absolute',
    top: 8,
    right: 8,
    width: 24,
    height: 24,
    borderRadius: 12,
    backgroundColor: '#FF6B6B',
    justifyContent: 'center',
    alignItems: 'center',
  },
  // Location
  locationHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 12,
  },
  locationContainer: {
    backgroundColor: 'rgba(255, 255, 255, 0.95)',
    borderRadius: 16,
    padding: 12,
    position: 'relative',
    marginTop: 12,
  },
  locationInput: {
    fontSize: 16,
    color: '#1a1a1a',
    minHeight: 50,
    paddingVertical: 10,
    paddingHorizontal: 10,
    backgroundColor: '#F5F5F5',
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#E0E0E0',
  },
  locationLoading: {
    position: 'absolute',
    top: 12,
    right: 12,
    paddingHorizontal: 10,
    paddingVertical: 6,
    backgroundColor: '#FFE5E5',
    borderRadius: 8,
  },
  locationLoadingText: {
    fontSize: 12,
    color: '#FF6B6B',
    fontWeight: '500',
  },
  // Attachments
  attachmentSection: {
    marginTop: 12,
  },
  attachmentButton: {
    borderRadius: 16,
    overflow: 'hidden',
    shadowColor: '#FF6B6B',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.2,
    shadowRadius: 8,
    elevation: 5,
  },
  attachmentButtonGradient: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 12,
    paddingHorizontal: 12,
    gap: 10,
  },
  attachmentButtonText: {
    fontSize: 16,
    fontWeight: '700',
    color: '#FFFFFF',
  },
  attachmentsContainer: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 12,
    marginTop: 12,
    paddingTop: 12,
    borderTopWidth: 1,
    borderTopColor: '#E0E0E0',
  },
  attachmentItem: {
    width: 100,
    height: 100,
    borderRadius: 12,
    overflow: 'hidden',
    position: 'relative',
    borderWidth: 2,
    borderColor: '#FFE5E5',
  },
  attachmentImage: {
    width: '100%',
    height: '100%',
    resizeMode: 'cover',
  },
  removeAttachmentButton: {
    position: 'absolute',
    top: -8,
    right: -8,
    backgroundColor: '#FFFFFF',
    borderRadius: 12,
  },
  submitButton: {
    marginTop: 12,
    marginBottom: 12,
    borderRadius: 50,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 12,
    paddingHorizontal: 12,
    minHeight: 56,
    shadowColor: '#FF5252',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.4,
    shadowRadius: 8,
    elevation: 6,
    overflow: 'hidden',
    position: 'relative',
  },
  submitButtonText: {
    fontSize: 18,
    fontWeight: '600',
    color: '#FFFFFF',
  },
  submitButtonDisabled: {
    shadowColor: '#E0E0E0',
    shadowOpacity: 0.2,
    elevation: 2,
    borderWidth: 2,
    borderColor: '#E0E0E0',
  },
  submitButtonTextDisabled: {
    color: '#888888',
    fontWeight: '500',
  },
  submitButtonIcon: {
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: '#FFFFFF',
    alignItems: 'center',
    justifyContent: 'center',
    position: 'absolute',
    right: 12,
  },
  submitButtonIconDisabled: {
    backgroundColor: '#F5F5F5',
  },

  // Profile Screen - Modernized
  profileHeader: {
    alignItems: 'center',
    marginTop: 30,
    marginBottom: 20,
    paddingHorizontal: 20,
    width: '100%',
  },
  profileHeaderTopRow: {
    width: '100%',
    flexDirection: 'row',
    alignItems: 'flex-start',
    justifyContent: 'space-between',
  },
  sectionHeaderRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 12,
  },
  profileAvatarContainer: {
    position: 'relative',
    marginBottom: 20,
  },
  avatarLarge: {
    width: 120,
    height: 120,
    borderRadius: 60,
    backgroundColor: '#fff',
    justifyContent: 'center',
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.15,
    shadowRadius: 20,
    elevation: 8,
    borderWidth: 4,
    borderColor: 'rgba(255, 255, 255, 0.3)',
  },
  avatarLargeText: {
    fontSize: 42,
    fontWeight: '800',
    color: '#FF6B6B',
    letterSpacing: 1,
  },
  avatarBadge: {
    position: 'absolute',
    bottom: 0,
    right: 0,
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: '#4CAF50',
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 3,
    borderColor: '#fff',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.2,
    shadowRadius: 4,
    elevation: 4,
  },
  profileName: {
    fontSize: 28,
    fontWeight: '800',
    color: '#fff',
    marginBottom: 8,
    textShadowColor: 'rgba(0, 0, 0, 0.15)',
    textShadowOffset: { width: 0, height: 2 },
    textShadowRadius: 4,
    letterSpacing: 0.5,
  },
  profileEmail: {
    fontSize: 16,
    color: 'rgba(255, 255, 255, 0.95)',
    fontWeight: '500',
    letterSpacing: 0.3,
  },
  profileEmailInput: {
    width: '100%',
    backgroundColor: 'rgba(255, 255, 255, 0.95)',
    borderRadius: 18,
    paddingVertical: 10,
    paddingHorizontal: 16,
    fontSize: 16,
    color: '#FF6B6B',
    marginTop: 4,
  },
  editIconButton: {
    padding: 8,
    borderRadius: 20,
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: '#FF6B6B',
    shadowColor: '#FF6B6B',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.2,
    shadowRadius: 4,
    elevation: 4,
  },
  editActionRow: {
    flexDirection: 'row',
    gap: 12,
    paddingHorizontal: 20,
    marginBottom: 20,
    width: '100%',
  },
  editButton: {
    flex: 1,
    borderRadius: 20,
    paddingVertical: 12,
    justifyContent: 'center',
    alignItems: 'center',
  },
  saveButton: {
    backgroundColor: '#FF6B6B',
    shadowColor: '#FF3B30',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.3,
    shadowRadius: 6,
    elevation: 4,
  },
  editButtonText: {
    fontSize: 15,
    fontWeight: '700',
    color: '#FF6B6B',
  },
  infoSection: {
    backgroundColor: 'rgba(255, 255, 255, 0.98)',
    borderRadius: 24,
    padding: 20,
    marginBottom: 20,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.1,
    shadowRadius: 12,
    elevation: 6,
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.5)',
  },
  infoCard: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 16,
    paddingHorizontal: 4,
    marginBottom: 4,
    borderRadius: 16,
    backgroundColor: 'transparent',
  },
  infoIconContainer: {
    width: 48,
    height: 48,
    borderRadius: 24,
    backgroundColor: '#FFF5F5',
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 16,
    shadowColor: '#FF6B6B',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 2,
  },
  infoContent: {
    flex: 1,
    paddingRight: 8,
  },
  infoLabel: {
    fontSize: 12,
    color: '#7A7A7A',
    marginBottom: 6,
    fontWeight: '600',
    letterSpacing: 0.5,
    textTransform: 'uppercase',
  },
  infoValue: {
    fontSize: 17,
    fontWeight: '700',
    color: '#1a1a1a',
    letterSpacing: 0.2,
  },
  infoInput: {
    marginTop: 4,
    paddingVertical: 6,
    paddingHorizontal: 10,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: 'rgba(255, 107, 107, 0.4)',
    backgroundColor: '#fff',
    fontSize: 16,
    color: '#1a1a1a',
  },
  logoutButton: {
    backgroundColor: '#FF3B30',
    borderRadius: 20,
    padding: 18,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 32,
    marginBottom: 24,
    marginHorizontal: 4,
    shadowColor: '#FF3B30',
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.3,
    shadowRadius: 12,
    elevation: 8,
    borderWidth: 0,
  },
  logoutButtonText: {
    fontSize: 18,
    fontWeight: '800',
    color: '#fff',
    marginLeft: 10,
    letterSpacing: 0.5,
  },

  // No Active Case
  noActiveCaseContainer: {
    justifyContent: 'center',
    alignItems: 'center',
    paddingVertical: 40,
    paddingHorizontal: 20,
  },
  noActiveCaseText: {
    fontSize: 18,
    fontWeight: '600',
    color: '#34C759',
    letterSpacing: 0.3,
    marginTop: 12,
  },
  noActiveCaseSubtext: {
    fontSize: 14,
    fontWeight: '400',
    color: '#999',
    marginTop: 8,
    textAlign: 'center',
  },

  // Active Case Section
  activeCaseContainer: {
    // --- POSITIONING CHANGE ---
    position: 'absolute',
    bottom: 90, // Adjust this value to clear your Bottom Navbar perfectly
    left: 12,
    right: 12,
    zIndex: 100, // Floats on top of everything else
    // --------------------------

    backgroundColor: 'rgba(255, 255, 255, 0.98)', // High opacity to hide content behind it
    borderRadius: 24,
    padding: 20,

    // Shadows (Slightly stronger upwards shadow for bottom sheets)
    shadowColor: '#000',
    shadowOffset: { width: 0, height: -4 }, // Negative height moves shadow up
    shadowOpacity: 0.1,
    shadowRadius: 12,
    elevation: 20,

    borderWidth: 1,
    borderColor: 'rgba(255, 107, 107, 0.2)', // Subtle red border

    // Responsive adjustments
    maxHeight: screenHeight * 0.6, // Maximum 60% of screen height
  },
  activeCaseContainerExpanded: {
    // When maximized, adjust bottom position and allow more height
    bottom: 90,
    maxHeight: screenHeight * 0.75, // Allow up to 75% of screen height when expanded
    minHeight: 200, // Minimum height to ensure content is visible
  },
  minimizeButton: {
    paddingHorizontal: 10,
    paddingVertical: 10,
    borderRadius: 10,
    backgroundColor: '#F5F5F5',
    marginLeft: 5,
  },
  activeCaseTitleRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  statusBadge: {
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 16,
  },
  statusText: {
    fontSize: 12,
    fontWeight: '700',
    color: '#fff',
    letterSpacing: 0.5,
    textTransform: 'uppercase',
  },
  caseDetailsContainer: {
    backgroundColor: '#F8F9FA',
    borderRadius: 16,
    padding: 16,
    marginBottom: 16,
    maxHeight: screenHeight * 0.4, // Limit height to prevent overflow
  },
  caseDetailRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 12,
    gap: 8,
  },
  caseDetailLabel: {
    fontSize: 14,
    fontWeight: '600',
    color: '#666',
    minWidth: 80,
  },
  caseDetailValue: {
    fontSize: 14,
    fontWeight: '700',
    color: '#1a1a1a',
    flex: 1,
  },
  caseDescriptionContainer: {
    marginTop: 8,
    marginBottom: 8,
    paddingTop: 12,
    borderTopWidth: 1,
    borderTopColor: '#E0E0E0',
  },
  caseDescriptionLabel: {
    fontSize: 14,
    fontWeight: '600',
    color: '#666',
    marginBottom: 8,
  },
  caseDescriptionText: {
    fontSize: 13,
    color: '#1a1a1a',
    lineHeight: 20,
  },
  messageContainer: {
    marginBottom: 16,
  },
  messageInput: {
    backgroundColor: '#F8F9FA',
    borderRadius: 16,
    padding: 16,
    fontSize: 16,
    color: '#1a1a1a',
    minHeight: 100,
    borderWidth: 1,
    borderColor: '#E0E0E0',
    textAlignVertical: 'top',
  },
  caseActionButtons: {
    gap: 12,
  },
  sendMessageButton: {
    backgroundColor: '#FF6B6B',
    borderRadius: 16,
    padding: 16,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    shadowColor: '#FF6B6B',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 4,
  },
  sendMessageButtonText: {
    fontSize: 16,
    fontWeight: '700',
    color: '#fff',
    letterSpacing: 0.3,
  },
  buttonDisabled: {
    opacity: 0.6,
  },
  cancelReportButton: {
    backgroundColor: 'transparent',
    borderRadius: 16,
    padding: 16,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    borderWidth: 2,
    borderColor: '#FF3B30',
    marginTop: 8,
  },
  cancelReportButtonText: {
    fontSize: 16,
    fontWeight: '700',
    color: '#FF3B30',
    letterSpacing: 0.3,
  },

  // Bottom Navigation
  bottomNav: {
    position: 'absolute',
    bottom: 0,
    left: 0,
    right: 0,
    backgroundColor: '#fff',
    flexDirection: 'row',
    justifyContent: 'space-around',
    alignItems: 'center',
    paddingVertical: 12,
    paddingBottom: Platform.OS === 'ios' ? 30 : 12,
    borderTopWidth: 1,
    borderTopColor: '#E0E0E0',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: -2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 5,
  },
  navItem: {
    alignItems: 'center',
    justifyContent: 'center',
    flex: 1,
  },
  navItemActive: {
    // Active state styling
  },
  navText: {
    fontSize: 12,
    color: '#999',
    marginTop: 4,
  },
  navTextActive: {
    color: '#FF6B6B',
    fontWeight: '600',
  },

  // Read-only styles
  readOnlyInput: {
    backgroundColor: '#F0F0F0',
    color: '#999',
    opacity: 0.7,
  },
  readOnlyButton: {
    opacity: 0.5,
  },

  // Floating Chat Head
  floatingChatHead: {
    position: 'absolute',
    bottom: 100,
    right: 20,
    width: 60,
    height: 60,
    borderRadius: 30,
    backgroundColor: '#FF6B6B',
    justifyContent: 'center',
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 8,
    zIndex: 1000,
  },
  chatHeadBadge: {
    position: 'absolute',
    top: -2,
    right: -2,
    width: 20,
    height: 20,
    borderRadius: 10,
    backgroundColor: '#FF3B30',
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 2,
    borderColor: '#FFFFFF',
  },
  chatHeadBadgeText: {
    color: '#FFFFFF',
    fontSize: 10,
    fontWeight: 'bold',
  },

  // Chat Modal
  chatModalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
    justifyContent: 'flex-end',
  },
  chatModalContainer: {
    backgroundColor: '#FFFFFF',
    borderTopLeftRadius: 28,
    borderTopRightRadius: 28,
    maxHeight: '85%',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: -4 },
    shadowOpacity: 0.1,
    shadowRadius: 12,
    elevation: 10,
  },
  chatModalHeader: {
    backgroundColor: '#FFFFFF',
    borderTopLeftRadius: 28,
    borderTopRightRadius: 28,
    paddingTop: 16,
    paddingBottom: 12,
    borderBottomWidth: 1,
    borderBottomColor: '#F0F0F0',
  },
  chatModalHeaderContent: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 20,
  },
  chatModalHeaderLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    flex: 1,
  },
  chatModalTitleContainer: {
    marginLeft: 12,
  },
  chatModalTitle: {
    fontSize: 20,
    fontWeight: '700',
    color: '#1a1a1a',
    letterSpacing: 0.3,
  },
  chatModalSubtitle: {
    fontSize: 12,
    color: '#999',
    marginTop: 2,
    fontWeight: '500',
  },
  chatModalCloseButton: {
    padding: 4,
  },
  chatModalContent: {
    flex: 1,
    paddingHorizontal: 16,
    paddingTop: 16,
  },
  chatModalOfficeInfo: {
    backgroundColor: '#F8F9FA',
    borderRadius: 16,
    padding: 16,
    marginBottom: 16,
    borderWidth: 1,
    borderColor: '#E8E8E8',
  },
  chatModalOfficeHeader: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  chatModalOfficeIconContainer: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: '#FFE5E5',
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 12,
  },
  chatModalOfficeTextContainer: {
    flex: 1,
  },
  chatModalOfficeName: {
    fontSize: 16,
    fontWeight: '600',
    color: '#1a1a1a',
    marginBottom: 6,
  },
  chatModalStatusContainer: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  chatModalStatusDot: {
    width: 8,
    height: 8,
    borderRadius: 4,
    marginRight: 6,
  },
  chatModalStatus: {
    fontSize: 13,
    color: '#666',
    fontWeight: '500',
    textTransform: 'capitalize',
  },
  chatMessagesContainer: {
    flex: 1,
    marginBottom: 16,
    paddingHorizontal: 4,
  },
  chatMessageWrapper: {
    marginBottom: 8,
    marginVertical: 4,
    flexDirection: 'row',
  },
  chatMessageWrapperUser: {
    justifyContent: 'flex-end',
  },
  chatMessageWrapperLeft: {
    justifyContent: 'flex-start',
  },
  chatMessage: {
    paddingHorizontal: 14,
    paddingVertical: 10,
    borderRadius: 18,
    maxWidth: '75%',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.1,
    shadowRadius: 2,
    elevation: 2,
  },
  chatMessageUser: {
    backgroundColor: '#34C759', // Green for CIVILIAN
    borderBottomRightRadius: 4,
  },
  chatMessagePolice: {
    backgroundColor: '#007AFF', // Blue for POLICE
    borderBottomLeftRadius: 4,
  },
  chatMessageText: {
    fontSize: 15,
    color: '#FFFFFF',
    lineHeight: 20,
  },
  chatMessageTextUser: {
    color: '#FFFFFF',
  },
  chatMessageTime: {
    fontSize: 11,
    marginTop: 4,
    fontWeight: '500',
  },
  chatMessageTimeUser: {
    color: 'rgba(255, 255, 255, 0.8)',
    textAlign: 'right',
  },
  chatMessageTimePolice: {
    color: 'rgba(255, 255, 255, 0.8)',
    textAlign: 'left',
  },
  chatEmptyState: {
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 60,
  },
  chatEmptyText: {
    fontSize: 16,
    color: '#999',
    marginTop: 16,
    fontWeight: '500',
  },
  chatEmptySubtext: {
    fontSize: 14,
    color: '#CCC',
    marginTop: 4,
  },
  chatInputContainer: {
    backgroundColor: '#FFFFFF',
    paddingHorizontal: 16,
    paddingVertical: 12,
    paddingBottom: 20,
    borderTopWidth: 1,
    borderTopColor: '#F0F0F0',
  },
  chatInputWrapper: {
    flexDirection: 'row',
    alignItems: 'flex-end',
    backgroundColor: '#F8F9FA',
    borderRadius: 24,
    paddingHorizontal: 4,
    paddingVertical: 4,
    borderWidth: 1,
    borderColor: '#E8E8E8',
  },
  chatInput: {
    flex: 1,
    fontSize: 15,
    color: '#1a1a1a',
    paddingHorizontal: 16,
    paddingVertical: 10,
    maxHeight: 100,
    textAlignVertical: 'top',
  },
  chatSendButton: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: '#FF6B6B',
    justifyContent: 'center',
    alignItems: 'center',
    marginLeft: 4,
    shadowColor: '#FF6B6B',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.3,
    shadowRadius: 4,
    elevation: 3,
  },
  chatSendButtonDisabled: {
    backgroundColor: '#E0E0E0',
    shadowOpacity: 0,
    elevation: 0,
  },

  // Notification Modal
  notificationModalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
    justifyContent: 'flex-end',
  },
  notificationModalContainer: {
    backgroundColor: '#FFFFFF',
    borderTopLeftRadius: 28,
    borderTopRightRadius: 28,
    maxHeight: '85%',
    minHeight: '50%',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: -4 },
    shadowOpacity: 0.1,
    shadowRadius: 12,
    elevation: 10,
  },
  notificationModalHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: 20,
    borderBottomWidth: 1,
    borderBottomColor: '#F0F0F0',
  },
  notificationModalTitle: {
    fontSize: 24,
    fontWeight: '800',
    color: '#1a1a1a',
    letterSpacing: 0.3,
  },
  notificationModalCloseButton: {
    padding: 4,
  },
  notificationModalContent: {
    flex: 1,
    paddingHorizontal: 20,
    paddingVertical: 16,
    minHeight: 200,
  },
  noNotificationsContainer: {
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 60,
  },
  noNotificationsText: {
    fontSize: 18,
    fontWeight: '600',
    color: '#666',
    marginTop: 16,
  },
  noNotificationsSubtext: {
    fontSize: 14,
    color: '#999',
    marginTop: 8,
    textAlign: 'center',
  },
  notificationItem: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#F8F9FA',
    borderRadius: 16,
    padding: 16,
    marginBottom: 12,
    borderWidth: 1,
    borderColor: '#E8E8E8',
  },
  notificationStatusIndicator: {
    width: 4,
    height: 50,
    borderRadius: 2,
    marginRight: 12,
  },
  notificationItemContent: {
    flex: 1,
  },
  notificationItemTitle: {
    fontSize: 16,
    fontWeight: '700',
    color: '#1a1a1a',
    marginBottom: 4,
  },
  notificationItemCategory: {
    fontSize: 14,
    color: '#666',
    marginBottom: 4,
    fontWeight: '500',
  },
  notificationItemTime: {
    fontSize: 12,
    color: '#999',
    fontWeight: '500',
  },

  // Notification Detail Panel
  notificationDetailOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  notificationDetailContainer: {
    backgroundColor: '#FFFFFF',
    borderRadius: 24,
    width: '85%',
    maxWidth: 400,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.2,
    shadowRadius: 12,
    elevation: 10,
  },
  notificationDetailHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: 20,
    borderBottomWidth: 1,
    borderBottomColor: '#F0F0F0',
  },
  notificationDetailTitle: {
    fontSize: 20,
    fontWeight: '800',
    color: '#1a1a1a',
    letterSpacing: 0.3,
  },
  notificationDetailCloseButton: {
    padding: 4,
  },
  notificationDetailContent: {
    padding: 32,
    alignItems: 'center',
    justifyContent: 'center',
  },
  notificationMessageContainer: {
    alignItems: 'center',
    justifyContent: 'center',
  },
  notificationMessageText: {
    fontSize: 18,
    fontWeight: '700',
    color: '#1a1a1a',
    textAlign: 'center',
    marginTop: 20,
    marginBottom: 8,
  },
  notificationMessageSubtext: {
    fontSize: 14,
    fontWeight: '500',
    color: '#666',
    textAlign: 'center',
  },
});

