import { Dimensions, StyleSheet } from 'react-native';

const { width: screenWidth, height: screenHeight } = Dimensions.get('window');
const buttonSize = Math.min(screenWidth * 0.5, 200);

// Responsive calculations
const isSmallDevice = screenWidth < 375;
const isMediumDevice = screenWidth >= 375 && screenWidth < 768;
const isLargeDevice = screenWidth >= 768;

// Calculate card width for report types
const getCardWidth = () => {
  const horizontalPadding = 40; // 20 on each side
  const gap = 12;
  let columns = 3;
  
  if (screenWidth < 320) {
    columns = 2; // Very small phones
  } else if (screenWidth >= 768) {
    columns = 4; // Tablets
  } else if (screenWidth >= 600) {
    columns = 4; // Large phones/small tablets
  }
  
  const totalGaps = gap * (columns - 1);
  const availableWidth = screenWidth - horizontalPadding - totalGaps;
  return availableWidth / columns;
};

const cardWidth = getCardWidth();

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#fff',
  },
  header: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: isSmallDevice ? 15 : 20,
    paddingVertical: isSmallDevice ? 12 : 15,
    backgroundColor: '#fff',
    borderBottomWidth: 1,
    borderBottomColor: '#e0e0e0',
  },
  greeting: {
    fontSize: 14,
    color: '#666',
  },
  userName: {
    fontSize: 24,
    fontWeight: 'bold',
    color: '#1a1a1a',
  },
  notificationButton: {
    position: 'relative',
  },
  notificationBadge: {
    position: 'absolute',
    top: 0,
    right: 0,
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: '#ff3b30',
  },
  content: {
    flex: 1,
  },
  welcomeCard: {
    backgroundColor: '#ff6b6b',
    margin: 20,
    padding: 20,
    borderRadius: 16,
  },
  welcomeTitle: {
    fontSize: 20,
    fontWeight: 'bold',
    color: '#fff',
    marginBottom: 5,
  },
  welcomeSubtitle: {
    fontSize: 14,
    color: '#fff',
    opacity: 0.9,
  },
  section: {
    paddingHorizontal: isSmallDevice ? 15 : 20,
    marginBottom: isSmallDevice ? 20 : 25,
  },
  sectionHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: isSmallDevice ? 12 : 15,
  },
  sectionTitle: {
    fontSize: isSmallDevice ? 16 : isLargeDevice ? 20 : 18,
    fontWeight: '700',
    color: '#1a1a1a',
  },
  addContactButton: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#ff6b6b20',
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#ff6b6b',
  },
  addContactButtonText: {
    fontSize: 14,
    fontWeight: '600',
    color: '#ff6b6b',
    marginLeft: 4,
  },
  actionsGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 12,
  },
  actionCard: {
    backgroundColor: '#fff',
    borderRadius: 16,
    padding: 20,
    width: '48%',
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
  },
  actionIcon: {
    width: 60,
    height: 60,
    borderRadius: 30,
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 10,
  },
  actionTitle: {
    fontSize: 14,
    fontWeight: '600',
    color: '#1a1a1a',
    textAlign: 'center',
  },
  activityCard: {
    backgroundColor: '#fff',
    borderRadius: 16,
    padding: 20,
    flexDirection: 'row',
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
  },
  activityContent: {
    marginLeft: 15,
    flex: 1,
  },
  activityTitle: {
    fontSize: 16,
    fontWeight: '600',
    color: '#1a1a1a',
    marginBottom: 3,
  },
  activitySubtitle: {
    fontSize: 14,
    color: '#666',
  },
  contactCard: {
    backgroundColor: '#fff',
    borderRadius: 16,
    padding: 20,
    marginBottom: 12,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
  },
  contactHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 8,
  },
  contactName: {
    fontSize: 16,
    fontWeight: '600',
    color: '#1a1a1a',
    marginLeft: 10,
    flex: 1,
  },
  deleteButton: {
    padding: 4,
    marginLeft: 8,
  },
  contactNumber: {
    fontSize: 18,
    fontWeight: '700',
    color: '#ff6b6b',
    marginLeft: 30,
    marginBottom: 10,
  },
  callButton: {
    flex: 1,
    flexDirection: 'row',
    backgroundColor: '#34C759',
    paddingHorizontal: 16,
    paddingVertical: 8,
    borderRadius: 8,
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
  },
  callButtonText: {
    fontSize: 14,
    fontWeight: '600',
    color: '#fff',
    marginLeft: 4,
  },
  actionButtons: {
    flexDirection: 'row',
    gap: 10,
    marginTop: 10,
  },
  messageButton: {
    flex: 1,
    flexDirection: 'row',
    backgroundColor: '#ff6b6b',
    paddingHorizontal: 16,
    paddingVertical: 8,
    borderRadius: 8,
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
  },
  messageButtonText: {
    fontSize: 14,
    fontWeight: '600',
    color: '#fff',
    marginLeft: 4,
  },
  noContactCard: {
    backgroundColor: '#fff',
    borderRadius: 16,
    padding: 30,
    alignItems: 'center',
    borderWidth: 1,
    borderColor: '#e0e0e0',
    borderStyle: 'dashed',
  },
  noContactText: {
    fontSize: 16,
    fontWeight: '600',
    color: '#8e8e93',
    marginTop: 12,
    marginBottom: 4,
  },
  noContactSubtext: {
    fontSize: 14,
    color: '#8e8e93',
    textAlign: 'center',
  },
  // Add Contact Modal Styles
  addContactModalContainer: {
    backgroundColor: '#fff',
    borderRadius: 20,
    padding: 0,
    width: isSmallDevice ? screenWidth * 0.9 : 400,
    maxHeight: screenHeight * 0.7,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 10,
  },
  addContactModalHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 20,
    paddingVertical: 20,
    borderBottomWidth: 1,
    borderBottomColor: '#e0e0e0',
  },
  addContactModalTitle: {
    fontSize: isSmallDevice ? 18 : 20,
    fontWeight: '700',
    color: '#1a1a1a',
  },
  closeButton: {
    padding: 4,
  },
  addContactForm: {
    padding: 20,
  },
  inputContainer: {
    marginBottom: 20,
  },
  inputLabel: {
    fontSize: 14,
    fontWeight: '600',
    color: '#1a1a1a',
    marginBottom: 8,
  },
  textInput: {
    backgroundColor: '#fff',
    borderRadius: 12,
    paddingHorizontal: 16,
    paddingVertical: 12,
    fontSize: 16,
    color: '#1a1a1a',
    borderWidth: 1,
    borderColor: '#e0e0e0',
  },
  addContactModalActions: {
    flexDirection: 'row',
    paddingHorizontal: 20,
    paddingVertical: 20,
    borderTopWidth: 1,
    borderTopColor: '#e0e0e0',
    gap: 12,
  },
  cancelModalButton: {
    flex: 1,
    backgroundColor: '#fff',
    paddingVertical: 12,
    borderRadius: 12,
    alignItems: 'center',
    borderWidth: 1,
    borderColor: '#e0e0e0',
  },
  cancelModalButtonText: {
    fontSize: 16,
    fontWeight: '600',
    color: '#8e8e93',
  },
  saveContactButton: {
    flex: 1,
    backgroundColor: '#ff6b6b',
    paddingVertical: 12,
    borderRadius: 12,
    alignItems: 'center',
    shadowColor: '#ff6b6b',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.2,
    shadowRadius: 4,
    elevation: 3,
  },
  saveContactButtonText: {
    fontSize: 16,
    fontWeight: '600',
    color: '#fff',
  },
  tabBar: {
    flexDirection: 'row',
    backgroundColor: '#fff',
    borderTopWidth: 1,
    borderTopColor: '#e0e0e0',
    paddingBottom: isSmallDevice ? 3 : 5,
    paddingTop: isSmallDevice ? 8 : 10,
  },
  tabItem: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: isSmallDevice ? 2 : 0,
  },
  tabLabel: {
    fontSize: isSmallDevice ? 10 : isLargeDevice ? 14 : 12,
    color: '#8e8e93',
    marginTop: isSmallDevice ? 2 : 4,
  },
  tabLabelActive: {
    color: '#ff6b6b',
    fontWeight: '600',
  },
  // Profile Screen Styles
  backButton: {
    padding: 5,
  },
  headerTitle: {
    fontSize: isSmallDevice ? 16 : isLargeDevice ? 22 : 18,
    fontWeight: '700',
    color: '#1a1a1a',
  },
  headerRight: {
    width: 34,
  },
  profileHeader: {
    alignItems: 'center',
    paddingVertical: 30,
    backgroundColor: '#fff',
    marginBottom: 20,
  },
  avatarContainer: {
    position: 'relative',
    marginBottom: 15,
  },
  avatar: {
    width: 100,
    height: 100,
    borderRadius: 50,
    backgroundColor: '#ff6b6b',
    justifyContent: 'center',
    alignItems: 'center',
    overflow: 'hidden',
  },
  avatarImage: {
    width: '100%',
    height: '100%',
    resizeMode: 'cover',
  },
  avatarText: {
    fontSize: 36,
    fontWeight: 'bold',
    color: '#fff',
  },
  cameraButton: {
    position: 'absolute',
    bottom: 0,
    right: 0,
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: '#ff6b6b',
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 3,
    borderColor: '#fff',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.2,
    shadowRadius: 4,
    elevation: 4,
  },
  profileName: {
    fontSize: 24,
    fontWeight: 'bold',
    color: '#1a1a1a',
    marginBottom: 5,
  },
  profileEmail: {
    fontSize: 14,
    color: '#666',
  },
  infoCard: {
    backgroundColor: '#fff',
    borderRadius: 16,
    padding: 15,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
  },
  infoRow: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 12,
    borderBottomWidth: 1,
    borderBottomColor: '#f0f0f0',
  },
  infoIconContainer: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: '#ff6b6b20',
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 15,
  },
  infoContent: {
    flex: 1,
  },
  infoLabel: {
    fontSize: 12,
    color: '#666',
    marginBottom: 3,
  },
  infoValue: {
    fontSize: 16,
    fontWeight: '600',
    color: '#1a1a1a',
  },
  logoutButton: {
    flexDirection: 'row',
    backgroundColor: '#ff3b30',
    marginHorizontal: 20,
    marginVertical: 30,
    padding: 16,
    borderRadius: 12,
    justifyContent: 'center',
    alignItems: 'center',
  },
  logoutButtonText: {
    fontSize: 16,
    fontWeight: '600',
    color: '#fff',
    marginLeft: 8,
  },
  // Report Screen Styles
  reportTypesGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 12,
    justifyContent: isSmallDevice ? 'space-between' : 'flex-start',
  },
  reportTypeCard: {
    backgroundColor: '#fff',
    borderRadius: isSmallDevice ? 12 : 16,
    padding: isSmallDevice ? 10 : isLargeDevice ? 20 : 15,
    width: cardWidth,
    minHeight: cardWidth * 1.2,
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
    position: 'relative',
  },
  reportTypeCardActive: {
    borderWidth: 2,
    borderColor: '#ff6b6b',
    backgroundColor: '#f0f8ff',
  },
  reportTypeIcon: {
    width: isSmallDevice ? 40 : isLargeDevice ? 60 : 50,
    height: isSmallDevice ? 40 : isLargeDevice ? 60 : 50,
    borderRadius: isSmallDevice ? 20 : isLargeDevice ? 30 : 25,
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: isSmallDevice ? 6 : 8,
  },
  reportTypeLabel: {
    fontSize: isSmallDevice ? 10 : isLargeDevice ? 14 : 12,
    fontWeight: '600',
    color: '#1a1a1a',
    textAlign: 'center',
    flexWrap: 'wrap',
    width: '100%',
  },
  checkmark: {
    position: 'absolute',
    top: isSmallDevice ? -3 : -5,
    right: isSmallDevice ? -3 : -5,
  },
  textArea: {
    backgroundColor: '#fff',
    borderRadius: 12,
    padding: isSmallDevice ? 12 : 15,
    fontSize: isSmallDevice ? 14 : isLargeDevice ? 18 : 16,
    color: '#1a1a1a',
    minHeight: isSmallDevice ? 100 : isLargeDevice ? 150 : 120,
    maxHeight: screenHeight * 0.3,
    borderWidth: 1,
    borderColor: '#e0e0e0',
  },
  input: {
    backgroundColor: '#fff',
    borderRadius: 12,
    padding: isSmallDevice ? 12 : 15,
    fontSize: isSmallDevice ? 14 : isLargeDevice ? 18 : 16,
    color: '#1a1a1a',
    borderWidth: 1,
    borderColor: '#e0e0e0',
    minHeight: isSmallDevice ? 45 : 50,
  },
  // Reporter Role Styles
  roleToggleContainer: {
    flexDirection: 'row',
    gap: 12,
    marginTop: 8,
  },
  roleButton: {
    flex: 1,
    backgroundColor: '#fff',
    borderRadius: 12,
    paddingVertical: isSmallDevice ? 14 : 16,
    paddingHorizontal: 20,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 2,
    borderColor: '#e0e0e0',
    minHeight: isSmallDevice ? 48 : 54,
  },
  roleButtonActive: {
    backgroundColor: '#ff6b6b20',
    borderColor: '#ff6b6b',
    borderWidth: 2,
  },
  roleButtonText: {
    fontSize: isSmallDevice ? 14 : isLargeDevice ? 18 : 16,
    fontWeight: '600',
    color: '#666',
  },
  roleButtonTextActive: {
    color: '#ff6b6b',
    fontWeight: '700',
  },
  // Attachments Styles
  attachButtonsRow: {
    marginTop: 8,
  },
  attachButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#fff',
    borderRadius: 12,
    paddingVertical: isSmallDevice ? 12 : 14,
    paddingHorizontal: 16,
    borderWidth: 2,
    borderColor: '#e0e0e0',
    borderStyle: 'dashed',
    gap: 8,
  },
  attachButtonText: {
    fontSize: isSmallDevice ? 14 : isLargeDevice ? 16 : 15,
    fontWeight: '600',
    color: '#666',
  },
  attachPreviewRow: {
    marginTop: 12,
    paddingVertical: 8,
  },
  attachItem: {
    position: 'relative',
    marginRight: 12,
  },
  attachThumbWrap: {
    width: isSmallDevice ? 80 : isLargeDevice ? 120 : 100,
    height: isSmallDevice ? 80 : isLargeDevice ? 120 : 100,
    borderRadius: 12,
    backgroundColor: '#f5f5f5',
    overflow: 'hidden',
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: '#e0e0e0',
  },
  attachThumb: {
    width: '100%',
    height: '100%',
    resizeMode: 'cover',
  },
  videoThumb: {
    backgroundColor: '#1a1a1a',
  },
  attachRemove: {
    position: 'absolute',
    top: -6,
    right: -6,
    backgroundColor: '#fff',
    borderRadius: 12,
    padding: 2,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.2,
    shadowRadius: 4,
    elevation: 4,
  },
  // SOS Button Styles
  sosContainer: {
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 40,
    marginBottom: 20,
  },
  sosButtonWrapper: {
    alignItems: 'center',
    justifyContent: 'center',
  },
  sosButton: {
    width: buttonSize,
    height: buttonSize,
    borderRadius: buttonSize / 2,
    backgroundColor: '#E8E8F0',
    justifyContent: 'center',
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.2,
    shadowRadius: 12,
    elevation: 10,
  },
  sosButtonInner: {
    width: buttonSize * 0.8,
    height: buttonSize * 0.8,
    borderRadius: (buttonSize * 0.8) / 2,
    backgroundColor: '#ff6b6b',
    justifyContent: 'center',
    alignItems: 'center',
  },
  sosText: {
    fontSize: buttonSize * 0.24,
    fontWeight: 'bold',
    color: '#fff',
    letterSpacing: 2,
  },
  sosSubtext: {
    fontSize: buttonSize * 0.06,
    color: '#fff',
    opacity: 0.9,
    marginTop: 4,
  },
  // Modal Styles
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.7)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  confirmationContainer: {
    backgroundColor: '#fff',
    borderRadius: 24,
    padding: 40,
    alignItems: 'center',
    minWidth: isSmallDevice ? screenWidth * 0.8 : 300,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 10,
  },
  confirmationTitle: {
    fontSize: isSmallDevice ? 24 : 28,
    fontWeight: 'bold',
    color: '#34C759',
    marginTop: 20,
    textAlign: 'center',
  },
  confirmationSubtitle: {
    fontSize: isSmallDevice ? 14 : 16,
    color: '#666',
    marginTop: 10,
    textAlign: 'center',
  },
});

